### ISSUE TITLE
start incorporating slush-graphic conveniences in an invisible way

### ISSUE THREAD

**Issue by gabrielflorit** [BostonGlobe/globe-graphic-template#8]

**Comment by russellsamora** [comment]
I actually had this but deleted it yesterday. I am going to re-instate in a simpler way. Starting with just babel, and maybe stylus (but I haven't found that as helpful for these inline graphics).

**Comment by russellsamora** [comment]
- [ ] update makefile for 2 options and delete extra files for basic version
- [ ] update readme for 2 options
- [ ] setup webpack compile and watch
- [ ] setup stylus compile and watch
